# Generated by Django 4.1.4 on 2023-01-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('flight_number', models.PositiveIntegerField(verbose_name='Flight Number')),
                ('flight_type', models.BooleanField(choices=[(0, 'scheduled'), (1, 'charter')], default=0, verbose_name='Flight Type')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='air.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_airplane', to='air.airplane')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_class', models.PositiveSmallIntegerField(choices=[(1, 'economy'), (2, 'business'), (3, 'first')], default=1, verbose_name='Flight Class')),
                ('price_for_one_passenger', models.PositiveIntegerField(default=1, verbose_name='Price for 1 Passenger')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_number_for_ticket', to='flight.flight')),
            ],
        ),
    ]
