# Generated by Django 4.1.4 on 2023-01-07 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city_or_section', models.CharField(max_length=100, verbose_name='City or Section')),
                ('address', models.TextField()),
                ('map_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid phone number.', 'invalid')])),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of Rooms')),
                ('floors', models.PositiveSmallIntegerField()),
                ('capacity', models.IntegerField()),
                ('area', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('star', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(verbose_name='Room Number')),
                ('floor', models.IntegerField()),
                ('area', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('single_beds', models.PositiveSmallIntegerField(verbose_name='Single Beds')),
                ('double_beds', models.PositiveSmallIntegerField(verbose_name='Double Beds')),
                ('extra_beds', models.PositiveSmallIntegerField(verbose_name='Extra Beds')),
                ('price_per_night', models.PositiveIntegerField(default=1, verbose_name='Price per Night')),
                ('is_valid', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_of_hotel_room', to='residence.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city_or_section', models.CharField(max_length=100, verbose_name='City or Section')),
                ('address', models.TextField()),
                ('map_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid phone number.', 'invalid')])),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of Rooms')),
                ('floors', models.PositiveSmallIntegerField()),
                ('capacity', models.IntegerField()),
                ('area', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('price_per_night', models.PositiveIntegerField(default=1, verbose_name='Price per Night')),
                ('residential_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residential', to='residence.residentialcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelRoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_feature', to='residence.hotelroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
