# Generated by Django 4.1.4 on 2023-01-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='phone_number',
        ),
    ]
