# Generated by Django 4.1.4 on 2023-01-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_number', models.PositiveIntegerField(default=uuid.uuid4, editable=False)),
                ('is_payed', models.BooleanField(default=True, verbose_name='Is payed')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('flight_ticket_reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.flightticketreservation', verbose_name='Flight Ticket Reservation')),
                ('hotel_room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.hotelroomreservation', verbose_name='Hotel Room Reservations')),
                ('residential_reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.residentialreservation', verbose_name='Residential Reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
