# Generated by Django 4.1.4 on 2023-01-07 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residence', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('checkin', models.DateField(auto_now=True)),
                ('checkout', models.DateField(auto_now=True)),
                ('count_of_nights', models.PositiveIntegerField(default=1)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residence.residential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('checkin', models.DateField(auto_now=True)),
                ('checkout', models.DateField(auto_now=True)),
                ('count_of_nights', models.PositiveIntegerField(default=1)),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residence.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightTicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.PositiveSmallIntegerField(default=1)),
                ('flight_ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flight.flightticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
